name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      # Install dependencies with caching
      # and run all Cypress tests
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4 
        with:
          role-to-assume: arn:aws:iam::521754508739:role/github 
          aws-region: eu-west-2
      - name: Get URI from SSM Parameter Store
        run: |
          URI=$(aws ssm get-parameter --name "apiuri" --query "Parameter.Value" --output text)
          echo "CYPRESS_BASE_URL=$URI" >> $GITHUB_ENV
      - name: Cypress run
        uses: cypress-io/github-action@v7