name: Deploy Frontend to S3

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write 

    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with: { repository: 'Louisobr/resume', token: '${{ secrets.PAT }}', path: 'private' }
      - run: pip install jinja2 && cp private/resume.json . && python build.py

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4 
        with:
          role-to-assume: arn:aws:iam::521754508739:role/github 
          aws-region: eu-west-2

      - name: Get URI from SSM Parameter Store
        run: |
          URI=$(aws ssm get-parameter --name "apiuri" --query "Parameter.Value" --output text)
          echo "API_URI=$URI" >> $GITHUB_ENV

      - name: Inject API URI into script.js
        run: |
          echo "const API_URI = '${{ env.API_URI }}';" > config.js

      - name: Sync files to S3
        
        run: |
          aws s3 sync . s3://cvbucket4949494 \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude ".gitignore" \
            --exclude "README.md" \
            --delete


      - name: Read CloudFront ID from SSM Parameter Store
        run: |
          CLOUDFRONT_ID=$(aws ssm get-parameter --name "cloudfrontid" --query "Parameter.Value" --output text)
          echo "CLOUDFRONT_ID=$CLOUDFRONT_ID" >> $GITHUB_ENV

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_ID }} --paths "/*"

